# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NerdKim's Log
email: younghun3869@gmail.com
description: nerd의 개발 공부 로그
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nerdkimdev.github.io" # the base hostname & protocol for your site
twitter_username: nerdKim
github_username:  nerdKim
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
